<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Member;
use Carbon\Carbon;

class MemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get user IDs for linking
        $adminUser = \App\Models\User::where('email', 'admin@kanisa.org')->first();
        $mhasibuUser = \App\Models\User::where('email', 'mhasibu@kanisa.org')->first();
        $memberUser = \App\Models\User::where('email', 'member@kanisa.org')->first();

        $members = [
            [
                'member_number' => 'MEM2025001',
                'envelope_number' => 'ENV20250001',
                'first_name' => 'John',
                'middle_name' => 'Peter',
                'last_name' => 'Mwangi',
                'date_of_birth' => '1985-03-15',
                'gender' => 'Mme',
                'phone' => '+255712345678',
                'email' => 'john.mwangi@email.com',
                'user_id' => $memberUser ? $memberUser->id : null,
                'occupation' => 'Mwalimu',
                'address' => 'Mbezi Beach, Dar es Salaam',
                'house_number' => 'HSE-101',
                'block_number' => 'BLK-A',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'baptism_date' => '1990-06-10',
                'confirmation_date' => '1998-05-20',
                'membership_date' => '2020-01-15',
                'marital_status' => 'Ameoa/Ameolewa',
                'spouse_name' => 'Mary Mwangi',
                'spouse_phone' => '+255712345679',
                'children_info' => json_encode([
                    ['name' => 'Grace Mwangi', 'age' => 12],
                    ['name' => 'David Mwangi', 'age' => 8]
                ]),
                'neighbor_name' => 'James Kamau',
                'neighbor_phone' => '+255712345680',
                'church_elder' => 'Mzee Joseph Kimani',
                'pledge_number' => 'PLD2025001',
                'special_group' => 'Wazazi',
                'ministry_groups' => json_encode(['Kwaya Kuu', 'Bibilia']),
                'id_number' => '19850315-12345-00001-67',
                'is_active' => true,
                'notes' => 'Mwanachama mwenye bidii katika huduma za kanisa',
            ],
            [
                'member_number' => 'MEM2025002',
                'envelope_number' => 'ENV20250002',
                'first_name' => 'Sarah',
                'middle_name' => 'Elizabeth',
                'last_name' => 'Moshi',
                'date_of_birth' => '1990-07-22',
                'gender' => 'Mke',
                'phone' => '+255754321098',
                'email' => 'sarah.moshi@email.com',
                'user_id' => $adminUser ? $adminUser->id : null,
                'occupation' => 'Muuguzi',
                'address' => 'Mikocheni, Dar es Salaam',
                'house_number' => 'HSE-205',
                'block_number' => 'BLK-B',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'baptism_date' => '1995-08-15',
                'confirmation_date' => '2003-07-10',
                'membership_date' => '2018-03-20',
                'marital_status' => 'Ameoa/Ameolewa',
                'spouse_name' => 'Daniel Moshi',
                'spouse_phone' => '+255754321099',
                'children_info' => json_encode([
                    ['name' => 'Emmanuel Moshi', 'age' => 5],
                    ['name' => 'Esther Moshi', 'age' => 3]
                ]),
                'neighbor_name' => 'Anna Mtui',
                'neighbor_phone' => '+255754321100',
                'church_elder' => 'Mama Grace Njau',
                'pledge_number' => 'PLD2025002',
                'special_group' => 'Akina Mama',
                'ministry_groups' => json_encode(['Kwaya ya Wanawake', 'Shule ya Jumapili']),
                'id_number' => '19900722-23456-00002-78',
                'is_active' => true,
                'notes' => 'Msaidizi wa kundi la uuguzi',
            ],
            [
                'member_number' => 'MEM2025003',
                'envelope_number' => 'ENV20250003',
                'first_name' => 'Emmanuel',
                'middle_name' => 'Joseph',
                'last_name' => 'Komba',
                'date_of_birth' => '2000-11-05',
                'gender' => 'Mme',
                'phone' => '+255765432109',
                'email' => 'emmanuel.komba@email.com',
                'user_id' => $mhasibuUser ? $mhasibuUser->id : null,
                'occupation' => 'Mwanafunzi - Chuo Kikuu',
                'address' => 'Ubungo, Dar es Salaam',
                'house_number' => 'HSE-310',
                'block_number' => 'BLK-C',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'baptism_date' => '2005-12-25',
                'confirmation_date' => '2013-06-15',
                'membership_date' => '2019-09-01',
                'marital_status' => 'Sijaoa/Sijaolewa',
                'children_info' => null,
                'neighbor_name' => 'Peter Nyerere',
                'neighbor_phone' => '+255765432110',
                'church_elder' => 'Mzee David Lyimo',
                'pledge_number' => 'PLD2025003',
                'special_group' => 'Vijana',
                'ministry_groups' => json_encode(['Kwaya ya Vijana', 'ICT Ministry']),
                'id_number' => '20001105-34567-00003-89',
                'is_active' => true,
                'notes' => 'Kiongozi wa vijana, msaidizi wa ICT',
            ],
            [
                'member_number' => 'MEM2025004',
                'envelope_number' => 'ENV20250004',
                'first_name' => 'Agnes',
                'middle_name' => 'Maria',
                'last_name' => 'Massawe',
                'date_of_birth' => '1975-02-14',
                'gender' => 'Mke',
                'phone' => '+255713456789',
                'email' => 'agnes.massawe@email.com',
                'occupation' => 'Mfanyabiashara',
                'address' => 'Kinondoni, Dar es Salaam',
                'house_number' => 'HSE-105',
                'block_number' => 'BLK-A',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'baptism_date' => '1980-04-20',
                'confirmation_date' => '1988-05-15',
                'membership_date' => '2015-07-10',
                'marital_status' => 'Mjane',
                'children_info' => json_encode([
                    ['name' => 'Michael Massawe', 'age' => 25],
                    ['name' => 'Ruth Massawe', 'age' => 22],
                    ['name' => 'Joseph Massawe', 'age' => 19]
                ]),
                'neighbor_name' => 'Elizabeth Mwakasege',
                'neighbor_phone' => '+255713456790',
                'church_elder' => 'Mama Joyce Mlimba',
                'pledge_number' => 'PLD2025004',
                'special_group' => 'Wajane',
                'ministry_groups' => json_encode(['Kwaya Kuu', 'Huduma za Wahitaji']),
                'id_number' => '19750214-45678-00004-90',
                'is_active' => true,
                'notes' => 'Mchungaji msaidizi wa kundi la wajane',
            ],
            [
                'member_number' => 'MEM2025005',
                'envelope_number' => 'ENV20250005',
                'first_name' => 'Joshua',
                'middle_name' => 'Samuel',
                'last_name' => 'Mwakyembe',
                'date_of_birth' => '1968-09-30',
                'gender' => 'Mme',
                'phone' => '+255724567890',
                'email' => 'joshua.mwakyembe@email.com',
                'occupation' => 'Mhandisi',
                'address' => 'Tegeta, Dar es Salaam',
                'house_number' => 'HSE-401',
                'block_number' => 'BLK-D',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'baptism_date' => '1973-10-15',
                'confirmation_date' => '1981-08-20',
                'membership_date' => '2010-02-28',
                'marital_status' => 'Ameoa/Ameolewa',
                'spouse_name' => 'Rebecca Mwakyembe',
                'spouse_phone' => '+255724567891',
                'children_info' => json_encode([
                    ['name' => 'Samuel Mwakyembe', 'age' => 30],
                    ['name' => 'Deborah Mwakyembe', 'age' => 27],
                    ['name' => 'Jonathan Mwakyembe', 'age' => 24]
                ]),
                'neighbor_name' => 'Francis Mhina',
                'neighbor_phone' => '+255724567892',
                'church_elder' => 'Mzee Benjamin Moshi',
                'pledge_number' => 'PLD2025005',
                'special_group' => 'Wazee',
                'ministry_groups' => json_encode(['Kwaya Kuu', 'Ushauri wa Ujenzi']),
                'id_number' => '19680930-56789-00005-01',
                'is_active' => true,
                'notes' => 'Mzee wa kanisa, mshauri wa miradi ya ujenzi',
            ],
            [
                'member_number' => 'MEM2025006',
                'envelope_number' => 'ENV20250006',
                'first_name' => 'Grace',
                'middle_name' => 'Neema',
                'last_name' => 'Ndunguru',
                'date_of_birth' => '1995-05-18',
                'gender' => 'Mke',
                'phone' => '+255755678901',
                'email' => 'grace.ndunguru@email.com',
                'occupation' => 'Mkaguzi wa Hesabu',
                'address' => 'Mbezi Luis, Dar es Salaam',
                'house_number' => 'HSE-210',
                'block_number' => 'BLK-B',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'baptism_date' => '2000-06-25',
                'confirmation_date' => '2008-09-14',
                'membership_date' => '2021-11-05',
                'marital_status' => 'Sijaoa/Sijaolewa',
                'children_info' => null,
                'neighbor_name' => 'Lucy Chambo',
                'neighbor_phone' => '+255755678902',
                'church_elder' => 'Mama Christina Ngowi',
                'pledge_number' => 'PLD2025006',
                'special_group' => 'Vijana',
                'ministry_groups' => json_encode(['Kwaya ya Wanawake', 'Bibilia']),
                'id_number' => '19950518-67890-00006-12',
                'is_active' => true,
                'notes' => 'Msaidizi wa mhasibu wa kanisa',
            ],
            [
                'member_number' => 'MEM2025007',
                'envelope_number' => 'ENV20250007',
                'first_name' => 'Peter',
                'middle_name' => 'Daniel',
                'last_name' => 'Msuya',
                'date_of_birth' => '2005-12-10',
                'gender' => 'Mme',
                'phone' => '+255766789012',
                'email' => 'peter.msuya@email.com',
                'occupation' => 'Mwanafunzi - Sekondari',
                'address' => 'Goba, Dar es Salaam',
                'house_number' => 'HSE-115',
                'block_number' => 'BLK-A',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'baptism_date' => '2010-08-15',
                'confirmation_date' => '2018-10-21',
                'membership_date' => '2022-01-16',
                'marital_status' => 'Sijaoa/Sijaolewa',
                'children_info' => null,
                'neighbor_name' => 'John Kileo',
                'neighbor_phone' => '+255766789013',
                'church_elder' => 'Mzee Paul Mgeni',
                'pledge_number' => 'PLD2025007',
                'special_group' => 'Vijana',
                'ministry_groups' => json_encode(['Kwaya ya Vijana', 'Michezo']),
                'id_number' => '20051210-78901-00007-23',
                'is_active' => true,
                'notes' => 'Mwanamuziki hodari, anacheza gitaa',
            ],
            [
                'member_number' => 'MEM2025008',
                'envelope_number' => 'ENV20250008',
                'first_name' => 'Joyce',
                'middle_name' => 'Ester',
                'last_name' => 'Kilave',
                'date_of_birth' => '1982-04-25',
                'gender' => 'Mke',
                'phone' => '+255717890123',
                'email' => 'joyce.kilave@email.com',
                'occupation' => 'Daktari',
                'address' => 'Bunju, Dar es Salaam',
                'house_number' => 'HSE-305',
                'block_number' => 'BLK-C',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'baptism_date' => '1987-07-12',
                'confirmation_date' => '1995-06-08',
                'membership_date' => '2017-04-22',
                'marital_status' => 'Ameoa/Ameolewa',
                'spouse_name' => 'Robert Kilave',
                'spouse_phone' => '+255717890124',
                'children_info' => json_encode([
                    ['name' => 'Anna Kilave', 'age' => 10],
                    ['name' => 'Benjamin Kilave', 'age' => 7]
                ]),
                'neighbor_name' => 'Martha Msigwa',
                'neighbor_phone' => '+255717890125',
                'church_elder' => 'Mama Rose Mwakawago',
                'pledge_number' => 'PLD2025008',
                'special_group' => 'Wazazi',
                'ministry_groups' => json_encode(['Huduma za Afya', 'Kwaya Kuu']),
                'id_number' => '19820425-89012-00008-34',
                'is_active' => true,
                'notes' => 'Msimamizi wa huduma za afya kanisani',
            ],
            [
                'member_number' => 'MEM2025009',
                'envelope_number' => 'ENV20250009',
                'first_name' => 'Michael',
                'middle_name' => 'George',
                'last_name' => 'Lyatuu',
                'date_of_birth' => '1998-08-07',
                'gender' => 'Mme',
                'phone' => '+255758901234',
                'email' => 'michael.lyatuu@email.com',
                'occupation' => 'Mwandishi wa Habari',
                'address' => 'Kawe, Dar es Salaam',
                'house_number' => 'HSE-220',
                'block_number' => 'BLK-B',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'baptism_date' => '2003-09-28',
                'confirmation_date' => '2011-11-13',
                'membership_date' => '2020-06-14',
                'marital_status' => 'Sijaoa/Sijaolewa',
                'children_info' => null,
                'neighbor_name' => 'Juma Mgaya',
                'neighbor_phone' => '+255758901235',
                'church_elder' => 'Mzee Thomas Msemo',
                'pledge_number' => 'PLD2025009',
                'special_group' => 'Vijana',
                'ministry_groups' => json_encode(['Media Ministry', 'Kwaya ya Vijana']),
                'id_number' => '19980807-90123-00009-45',
                'is_active' => true,
                'notes' => 'Msimamizi wa media na mawasiliano',
            ],
            [
                'member_number' => 'MEM2025010',
                'envelope_number' => 'ENV20250010',
                'first_name' => 'Ruth',
                'middle_name' => 'Anna',
                'last_name' => 'Swai',
                'date_of_birth' => '1972-01-20',
                'gender' => 'Mke',
                'phone' => '+255769012345',
                'email' => 'ruth.swai@email.com',
                'occupation' => 'Meneja - Benki',
                'address' => 'Msasani, Dar es Salaam',
                'house_number' => 'HSE-405',
                'block_number' => 'BLK-D',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'baptism_date' => '1977-02-13',
                'confirmation_date' => '1985-03-10',
                'membership_date' => '2012-08-19',
                'marital_status' => 'Ameoa/Ameolewa',
                'spouse_name' => 'Jacob Swai',
                'spouse_phone' => '+255769012346',
                'children_info' => json_encode([
                    ['name' => 'Faith Swai', 'age' => 28],
                    ['name' => 'Hope Swai', 'age' => 25],
                    ['name' => 'Love Swai', 'age' => 22]
                ]),
                'neighbor_name' => 'Sarah Kisamo',
                'neighbor_phone' => '+255769012347',
                'church_elder' => 'Mama Deborah Tesha',
                'pledge_number' => 'PLD2025010',
                'special_group' => 'Wazee',
                'ministry_groups' => json_encode(['Kwaya ya Wanawake', 'Ushauri wa Fedha']),
                'id_number' => '19720120-01234-00010-56',
                'is_active' => true,
                'notes' => 'Mshauri wa mambo ya fedha za kanisa',
            ],
        ];

        foreach ($members as $member) {
            Member::create($member);
        }

        $this->command->info('✓ 10 wanachama wameongezwa successfully!');
    }
}
